### ISSUE TITLE
why do I need to specify the seg_list.txt during network-apply?

### ISSUE THREAD

**Issue by steelexu** [tarolangner/fcn_vatsat#1]
it's confusing the seg should be the output of network apply, I can't specify anything in seg_list.txt for the volumeToSlices

Thanks

**Comment by tarolangner** [comment]
Hey, sorry for the later answer. 

That part of the code was supposed to generate training or evaluation data, but it's true that if you just apply the network then there is no point in having input segmentations. I just committed a new version which no longer uses input segmentations, so that should hopefully clear things up.

Thanks for the feedback!
